language: go
go_import_path: github.com/ReconfigureIO/fixed

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux
      os: linux
go:
  - 1.9

install:
- curl -LO https://s3.amazonaws.com/reconfigure.io/reco/releases/reco-master-x86_64-linux.zip
- unzip reco-master-x86_64-linux.zip
- sudo mv reco /usr/local/bin

script:
  - make test
